<center>

# **Numpy: Tutorial**

</center>

---

**Author:** Isaac Cantú


**Date:** 06/04/2026



> **NumPy library**



In [1]:
import numpy as np

> **Basics**

In [16]:
# Vector
vector = np.array([1,2,3], dtype="int16") 
print(vector)

[1 2 3]


In [10]:
# Matrix
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [8]:
# Shape
matrix.shape

(2, 3)

In [14]:
# Dimensions
matrix.ndim

2

In [24]:
# Type
vector.dtype

dtype('int16')

In [26]:
# Size (number of bytes)
vector.itemsize

2

In [29]:
# total size n_bytes * elements
vector.nbytes

6

> **Accessing/changing elements, rows, columns, ...**

In [30]:
print(matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Specific element [r,c], r=rows, c=columns
matrix[0,0]

np.int64(1)

In [32]:
matrix[1,2]

np.int64(6)

In [34]:
# Row
matrix[0,:]

array([1, 2, 3])

In [35]:
# Column
matrix[:,1]

array([2, 5])

In [39]:
# Secifics elements [startindex:endindex:stepsize]
matrix[0, 1:3]

array([2, 3])

In [41]:
matrix[:, 0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
matrix[:,-1]

array([3, 6])

In [47]:
# Change value
matrix[0,0] = 10
print(matrix)

[[10  2  3]
 [ 4  5  6]]


In [48]:
# Change vectors
matrix[:, -1] = [100,100]
print(matrix)

[[ 10   2 100]
 [  4   5 100]]


> **Tensor**

In [52]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]],dtype="int8")
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int8)

In [54]:
tensor.shape

(2, 2, 2)

In [55]:
tensor[0,1,1]

np.int8(4)

In [57]:
# Replace
tensor[:,0,:] = [[10,10],[11,11]]
tensor

array([[[10, 10],
        [ 3,  4]],

       [[11, 11],
        [ 7,  8]]], dtype=int8)

> **Initializing arrays**

In [ ]:
# All zeros
np.zeros((2,2), dtype="int8")

array([[0, 0],
       [0, 0]], dtype=int8)

In [63]:
# All ones
np.ones((1,3,4))


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [64]:
# Other number
np.full((3,3), 100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [65]:
# Other number
np.full_like((3,3), 11)

array([11, 11])

In [ ]:
# Random numbers
np.random.rand(4,2)

array([[0.43035373, 0.74833365],
       [0.43995032, 0.97137566],
       [0.46258645, 0.37747212],
       [0.47250118, 0.91669033]])

In [80]:
# Random ints

np.random.randint(5,10, size=(3,3))

array([[5, 9, 6],
       [5, 6, 7],
       [7, 7, 9]])

In [81]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [88]:
arr = np.array([1,2,3])
np.repeat(arr,3,axis=0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [94]:
arr = np.array([[[1,2,3]]])
np.repeat(arr,3,axis=2)

array([[[1, 1, 1, 2, 2, 2, 3, 3, 3]]])

In [110]:
example = np.ones((5,5),dtype="int8")
print(example)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [112]:
example[1:4,1:4] = 0
example[2,2] = 9
example

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

> **Copying arrays**

In [116]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [118]:
b[0] = 100
print(b, a)

[100   2   3] [100   2   3]


In [119]:
a = np.array([1,2,3])
b = a.copy()
b

array([1, 2, 3])

In [120]:
b[0] = 100
print(b, a)

[100   2   3] [1 2 3]


> **Mathematics**

In [129]:
a = np.array(list(range(1,6)))
a

array([1, 2, 3, 4, 5])

In [130]:
a + 1 

array([2, 3, 4, 5, 6])

In [131]:
a - 1 

array([0, 1, 2, 3, 4])

In [132]:
a * 10

array([10, 20, 30, 40, 50])

In [133]:
a / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [134]:
a + a

array([ 2,  4,  6,  8, 10])

In [136]:
a ** 2 

array([ 1,  4,  9, 16, 25])

In [137]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

> **linear algebra**

In [140]:
m1 = np.full((2,2),9)
m2 = np.full((2,2),3)
np.matmul(m1,m2)

array([[54, 54],
       [54, 54]])

In [144]:
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

> **Statistics**

In [146]:
a = np.array(list(range(1,6)))
a

array([1, 2, 3, 4, 5])

In [147]:
np.min(a)

np.int64(1)

In [148]:
np.max(a)

np.int64(5)

In [149]:
np.sum(a)

np.int64(15)

In [151]:
np.mean(a)

np.float64(3.0)

> **Reorganizing arrays**

In [153]:
array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [162]:
array.reshape((5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [164]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

np.vstack([a1,a2])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])